### ISSUE TITLE
deconstructing adsense plugin

### ISSUE THREAD

**Issue by snjqi188** [team-melbourne-rgsoc2015/discourse#1]
trying to make sense of this since we'll be creating our own adv plugin.

this is the adsense.js.es6  we gathered from the [discourse adsense plugin by michaelid](https://meta.discourse.org/t/google-adsense-plugin/11763)

ps: wonder if there's any easier way to communicate this.. would wiki be better?

will be updating as we annotate along and deconstruct what each line does.

![screen shot 2015-07-08 at 9 09 09 am](https://cloud.githubusercontent.com/assets/10699989/8559516/ea8d45ea-2550-11e5-9d2a-3dee724d4f71.png)

@jocranford @adelsmee @georg @link664

**Comment by snjqi188** [comment]
(using a .rb file because the colours help reading)

![screen shot 2015-07-08 at 12 16 23 pm](https://cloud.githubusercontent.com/assets/10699989/8561595/22533bd2-256b-11e5-8093-e8fd9c107720.png)

**Comment by snjqi188** [comment]
![screen shot 2015-07-08 at 3 06 08 pm](https://cloud.githubusercontent.com/assets/10699989/8563442/c065463c-2582-11e5-86b4-0e77772b7f60.png)

**Comment by eviltrout** [comment]
It might be easier to answer questions if you posted your source instead of screenshots. It's really hard for me to read this way :(

**Comment by snjqi188** [comment]
[Here's](https://drive.google.com/file/d/0B0MprGf2iwLoZzJtM1IwbGJCcU0/view?usp=sharing) the source to the code (the adsense plugin we've been looking at) above! Thanks @eviltrout.

**Comment by snjqi188** [comment]
DONE. only one question left in the pull request of the discourse-adsense repo. Thanks @compactcode  of Redbubble for your help today!
